### ISSUE TITLE
main error

### ISSUE THREAD

**Issue by sdasara95** [Eitol/tobii_eye_tracker_linux_installer#1]
Hi,
I am facing an error when I'm running your main code.
I think the error is due to the linking of the shared libraries.
Did you do anything for this :
/usr/lib/tobii/libtobii_stream_engine.so

This .so file is not in my usr/lib/tobii
Infact, there is not directory 'tobii' in my usr/lib
I have run "sudo /sbin/ldconfig -v", still no change

**Comment by Eitol** [comment]
hi. Fixed. Pull and rerun the installer bash

**Comment by sdasara95** [comment]
I am now getting the .so file in usr/lib/tobii and am able to gcc compile your main file.
However, I'm getting this error:

./main: error while loading shared libraries: libtobii_stream_engine.so: cannot open shared object file: No such file or directory

**Comment by sdasara95** [comment]
Okay! I found the issue.
In the following file:
/etc/ld.so.conf

we have to edit it as follows:

include /etc/ld.so.conf.d/*.conf
/usr/lib/
/usr/lib/tobii/

This way the dynamic linker will also look for the files in the above folder during runtime.
Since our .so file is in "/usr/lib/tobii/" we have to give it's path in the conf file.
Else, it won't look in that directory and we will get the error in my above post.

**Comment by harsh183** [comment]
I am getting the same issue (shared libraries) despite trying the above fix. Based off running the install script Feb 18 2020.

```bash
.../example> gcc main.cpp -o main -pthread /usr/lib/tobii/libtobii_stream_engine.so
.../example> ./main
./main: error while loading shared libraries: libtobii_stream_engine.so: cannot open shared object file: No such file or directory
```

My `/etc/ld.so.conf.d/*.conf` is 
```
include /etc/ld.so.conf.d/*.conf
/usr/lib/
/usr/lib/tobii/
```

The library does exist in `/usr/lib/tobii`

```bash
/usr/lib/tobii > ll
total 2.7M
-rwxr-xr-x 1 harsh183 harsh183 2.7M Feb 18 01:25 libtobii_stream_engine.so*
```
