### ISSUE TITLE
Driver download on Manjaro

### ISSUE THREAD

**Issue by dev-goalz** [Eitol/tobii_eye_tracker_linux_installer#2]
Hi,
Very cool that you fixed this! Saw the YouTube video too.
I'm trying to get this working on Manjaro (Arch based). I converted the .deb files alright and they seem to work. The Tobii Manager does start for example. But I cannot find the 4c USB driver anywhere..

In the application I found this, it will list all driver downloads but its only for Windows and MacOS.
https://s3-eu-west-1.amazonaws.com/download.tobii.com/public/drivers/4c.json

How did you find the driver?

**Comment by Eitol** [comment]
Hello, really no idea. Tobii support for linux is very poor.

**Comment by dev-goalz** [comment]
Thanks for your reply that didn't add anything.
