### ISSUE TITLE
Broken link to Eye Tracker Manager

### ISSUE THREAD

**Issue by grafov** [Eitol/tobii_eye_tracker_linux_installer#4]
It seems like the right URL now is:
https://www.tobiipro.com/product-listing/eye-tracker-manager/

It follows to the common page with downloads for all OS but the [direct link points to S3](https://s3-eu-west-1.amazonaws.com/tobiipro.eyetracker.manager/tobiipro.etm.linux.html) and I afraid it could be changed at any time.

Please fix it in the README.

Thank you for this project! I'm considering buying the Tobii 4C that is available in my city. But the lack of Linux support was stopping me from this. I would hack the tracker for personal use as a directional device instead of a keyboard/trackball in multimonitor configuration.

**Comment by Eitol** [comment]
thanks!. Fixed
