### ISSUE TITLE
Security Concerns

### ISSUE THREAD

**Issue by ShockedCoder** [Eitol/tobii_eye_tracker_linux_installer#9]
I was about to install the provided Debian packages, however, I realized `tobii-config` and `tobiiproeyetrackermanager` have `cryptoseed` as their dependencies.

**This is very concerning**, as there is no reason for an eye-tracking software to need something which is used for **securing Bitcoin wallets recovery seeds.**

The other concerning part is that I cannot find the Debian installation files you have provided anywhere else on the internet.
No matter how or what I search, the only result that comes up is this repository. 

I would like to know where these installation files came from and why `cryptoseed` is needed as their dependency.

**Comment by Eitol** [comment]
I understand what you indicate. It also seems strange to me that it has such a strange dependency. I have taken these installers from the tobii website but they no longer exist.

**Comment by Eitol** [comment]
I understand what you indicate. It also seems strange to me that it has such a strange dependency. I have taken these installers from the tobii website but they no longer exist.

**Comment by ShockedCoder** [comment]
Can you prove this in anyway? A proof of their existence i.e. talked about on forums, screenshots the files being available on the website, anything?
While an [archive](https://archive.org) link would be great, even just a mention from anywhere else on the internet would be good enough.

I do apologize if I'm coming off a bit strong, but it is very hard to trust random files around the internet.

**Comment by t184256** [comment]
> I realized tobii-config and tobiiproeyetrackermanager have cryptoseed as their dependencies.

What are you talking about? Where is the dependency?

> Package: tobiiproeyetrackermanager
> Depends: libappindicator1, libnotify-bin
> (from control.tar.gz/control)

> While an archive link would be great

Tobii didn't offer downloads in the open, one had to be logged in.

**Comment by Eitol** [comment]
> Can you prove this in anyway? A proof of their existence i.e. talked about on forums, screenshots the files being available on the website, anything?
> While an [archive](https://archive.org) link would be great, even just a mention from anywhere else on the internet would be good enough.
> 
> I do apologize if I'm coming off a bit strong, but it is very hard to trust random files around the internet.

I have no proof. I just needed to use this for a project and thought it would be helpful to share how I did it and attach the installers. I can clearly understand if you don't trust

**Comment by Eitol** [comment]
> Can you prove this in anyway? A proof of their existence i.e. talked about on forums, screenshots the files being available on the website, anything?
> While an [archive](https://archive.org) link would be great, even just a mention from anywhere else on the internet would be good enough.
> 
> I do apologize if I'm coming off a bit strong, but it is very hard to trust random files around the internet.

I have no proof. I just needed to use this for a project and thought it would be helpful to share how I did it and attach the installers. I can clearly understand if you don't trust

**Comment by ShockedCoder** [comment]
> What are you talking about? Where is the dependency?

![image](https://github.com/Eitol/tobii_eye_tracker_linux_installer/assets/40272709/8556fade-ea6e-4d0b-934c-42a27bb77688)
tbf I should've attached this screenshot along with the start of the issue.

> I have no proof. I just needed to use this for a project and thought it would be helpful to share how I did it and attach the installers. I can clearly understand if you don't trust

Yeah, mb for creating this issue anyway, had to stop using the eye tracker anyway cuz it starts to hurt my eyes after ~20 mins of usage.
I'm sure there's nothing wrong with the packages and the tobii linux devs were just doin' some weird things.
